replicaCount: 1

image:
  repository: dapr-repro
  tag: latest
  pullPolicy: IfNotPresent

rabbit:
  host: rabbitmq.rabbit.svc.cluster.local
  port: "5672"
  username: rabbit
  password: rabbit
  incomingExchange: incoming-events
  incomingQueue: dapr-repro-incoming-events
  completionExchange: completed-events
