apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-repro
  labels:
    app: dapr-repro
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dapr-repro
  template:
    metadata:
      labels:
        app: dapr-repro
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: dapr-repro
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: RABBITMQ_URL
              value: "amqp://{{ .Values.rabbit.username }}:{{ .Values.rabbit.password }}@{{ .Values.rabbit.host }}:{{ .Values.rabbit.port }}"
            - name: INCOMING_EXCHANGE
              value: {{ .Values.rabbit.incomingExchange | quote }}
            - name: INCOMING_QUEUE
              value: {{ .Values.rabbit.incomingQueue | quote }}
            - name: COMPLETION_EXCHANGE
              value: {{ .Values.rabbit.completionExchange | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
