apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.dapr.pubsubName }}
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://{{ .Values.rabbit.username }}:{{ .Values.rabbit.password }}@{{ .Values.rabbit.host }}:{{ .Values.rabbit.port }}"
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: deliveryMode
      value: "2"
    - name: prefetchCount
      value: "1"
    - name: reconnectWait
      value: "0"
    - name: enableDeadLetter
      value: "true"
    - name: exchangeKind
      value: topic
