apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqs-incoming
spec:
  type: bindings.aws.sqs
  version: v1
  metadata:
    - name: queueName
      value: {{ .Values.aws.queueName }}
    - name: region
      value: {{ .Values.aws.region }}
    - name: direction
      value: "input"
    {{- if .Values.aws.accessKey }}
    - name: accessKey
      value: {{ .Values.aws.accessKey | quote }}
    {{- end }}
    {{- if .Values.aws.secretKey }}
    - name: secretKey
      value: {{ .Values.aws.secretKey | quote }}
    {{- end }}
    {{- if .Values.aws.sessionToken }}
    - name: sessionToken
      value: {{ .Values.aws.sessionToken | quote }}
    {{- end }}
  scopes:
    - {{ .Values.dapr.appId }}
